/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.farhanfadhilah.goacademycalculator;

import java.text.DecimalFormat;
import java.util.Scanner;

public class App {
    boolean isExit = false;
    double displayedNumber = 0.0;
    DecimalFormat numberFormat = new DecimalFormat("#0.0");

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        App calculator = new App();
        while (!calculator.isExit) {
            System.out.println(calculator.toString());
            System.out.println("Enter a command : ");
            String userInput = input.nextLine();
            String[] commands = userInput.split(" ");
            String commandWord = commands[0];
            int commandNumber = 0;
            if (commands.length == 2) {
                commandNumber = Integer.parseInt(commands[1]);
            }
            calculator.calculate(commandWord, commandNumber);
        }
        System.out.println();
    }

    @Override
    public String toString() {
        return String.valueOf(numberFormat.format(displayedNumber));
    }

    public boolean isExit() {
        isExit = !isExit;
        return isExit;
    }

    public void cancel() {
        displayedNumber = 0.0;
    }

    public void add(int commandNumber) {
        displayedNumber += commandNumber;
    }

    public void subtract(int commandNumber) {
        displayedNumber -= commandNumber;
    }

    public void multiply(int commandNumber) {
        displayedNumber *= commandNumber;
    }

    public void divide(int commandNumber) {
        if (commandNumber == 0) cancel();
        else displayedNumber /= commandNumber;
    }

    public void calculate(String commandWord, int commandNumber) {
        switch (commandWord) {
            case "add":
                add(commandNumber);
                break;
            case "subtract":
                subtract(commandNumber);
                break;
            case "multiply":
                multiply(commandNumber);
                break;
            case "divide":
                divide(commandNumber);
                break;
            case "cancel":
                cancel();
                break;
            case "exit":
                isExit();
                break;
            default:
        }
    }
}
