/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.farhanfadhilah.goacademycalculator;

import java.text.DecimalFormat;
import java.util.Scanner;

public class App {
    boolean isExit = false;
    double displayedNumber = 0.0;
    DecimalFormat numberFormat = new DecimalFormat("#0.0");

    @Override
    public String toString() {
        return String.valueOf(numberFormat.format(displayedNumber));
    }

    public boolean isExit() {
        isExit = !isExit;
        return isExit;
    }

    public String cancel() {
        displayedNumber = 0.0;
        return toString();
    }

    public String add(double firstNumber, int secondNumber) {
        displayedNumber = firstNumber + secondNumber;
        return toString();
    }

    public String subtract(double firstNumber, int secondNumber) {
        displayedNumber = firstNumber - secondNumber;
        return toString();
    }

    public String multiply(double firstNumber, int secondNumber) {
        displayedNumber = firstNumber * secondNumber;
        return toString();
    }

    public String divide(double firstNumber, int secondNumber) {
        displayedNumber = firstNumber / secondNumber;
        return toString();
    }

    public String calculate(String command) {
        String[] splitCommand = command.split(" ");
        String commandWord = splitCommand[0];

        if (splitCommand.length == 2) {
            int commandNumber = Integer.parseInt(splitCommand[1]);

            switch (commandWord) {
                case "add":
                    add(displayedNumber, commandNumber);
                    break;
                case "subtract":
                    subtract(displayedNumber, commandNumber);
                    break;
                case "multiply":
                    multiply(displayedNumber, commandNumber);
                    break;
                case "cancel":
                    cancel();
                    break;
                case "exit":
                    isExit();
                    break;
                default:
            }
        }
        return command;
    }

    public void main(String[] args) {
        System.out.println(toString());
        System.out.println();
    }
}
